image: docker:stable

services:
  - name: docker:dind
    command: ["--insecure-registry=solar.lan:5000"]

variables:
  CONTAINER_IMAGE: solar.lan:5000/docker-cache/$CI_PROJECT_PATH
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

build:
  stage: build
  script:
    - docker build --tag $CONTAINER_IMAGE:$CI_COMMIT_SHA --tag $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA
    - docker push $CONTAINER_IMAGE:latest

deploy:
  stage: deploy
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker pull $CONTAINER_IMAGE:$CI_COMMIT_SHA || true
    - docker tag $CONTAINER_IMAGE:$CI_COMMIT_SHA lierdakil/pandoc-crossref-build:$CI_COMMIT_SHA
    - docker tag $CONTAINER_IMAGE:$CI_COMMIT_SHA lierdakil/pandoc-crossref-build:latest
    - docker push lierdakil/pandoc-crossref-build:$CI_COMMIT_SHA
    - docker push lierdakil/pandoc-crossref-build:latest
  environment:
    name: latest
  only:
  - master
