name: Docker Image CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/lierdakil/pandoc-crossref-build/pandoc-crossref-build:$GITHUB_SHA
    - name: Push
      run: |
        docker login docker.pkg.github.com --username lierdakil --password "${{secrets.GITHUB_TOKEN}}"
        docker push docker.pkg.github.com/lierdakil/pandoc-crossref-build/pandoc-crossref-build:$GITHUB_SHA
        docker tag docker.pkg.github.com/lierdakil/pandoc-crossref-build/pandoc-crossref-build:$GITHUB_SHA docker.pkg.github.com/lierdakil/pandoc-crossref-build/pandoc-crossref-build:latest
        docker push docker.pkg.github.com/lierdakil/pandoc-crossref-build/pandoc-crossref-build:latest
